from reportlab.lib.pagesizes import A4
from reportlab.pdfgen import canvas
from reportlab.lib.styles import getSampleStyleSheet
from reportlab.platypus import SimpleDocTemplate, Paragraph, Spacer
from reportlab.lib.units import cm
import uuid
import os

class PDFService:

    @staticmethod
    def generate_report_pdf(report: dict):
        file_path = f"/tmp/{uuid.uuid4()}.pdf"

        doc = SimpleDocTemplate(
            file_path,
            pagesize=A4,
            rightMargin=2*cm,
            leftMargin=2*cm,
            topMargin=2*cm,
            bottomMargin=2*cm
        )

        styles = getSampleStyleSheet()
        story = []

        # Title
        story.append(
            Paragraph(
                "<b>CoughLens AI — Medical Report</b>",
                styles["Title"]
            )
        )
        story.append(Spacer(1, 12))

        # Body
        story.append(Paragraph(
            f"<b>Patient ID:</b> {report['patient_id']}",
            styles["Normal"]
        ))

        story.append(Paragraph(
            f"<b>Prediction:</b> {report['prediction']}",
            styles["Normal"]
        ))

        story.append(Paragraph(
            f"<b>Confidence:</b> {report['confidence'] * 100:.2f}%",
            styles["Normal"]
        ))

        story.append(Spacer(1, 12))

        story.append(Paragraph(
            "This report was generated using AI-powered cough sound analysis. "
            "It is intended for screening purposes only and not as a definitive diagnosis.",
            styles["Normal"]
        ))

        story.append(Spacer(1, 12))

        story.append(Paragraph(
            "Generated by <b>CoughLens AI</b>",
            styles["Italic"]
        ))

        doc.build(story)

        return file_path
