// shared/intents.ts

export const INTENTS = {
  // System
  CHANGE_LANGUAGE: "CHANGE_LANGUAGE",
  HELP: "HELP",
  STOP: "STOP",
  REPEAT_LAST: "REPEAT_LAST",

  // Patient
  ADD_PATIENT: "ADD_PATIENT",
  UPDATE_PATIENT: "UPDATE_PATIENT",
  GET_PATIENT_HISTORY: "GET_PATIENT_HISTORY",
  LIST_MY_PATIENTS: "LIST_MY_PATIENTS",

  // Cough / ML
  START_COUGH_TEST: "START_COUGH_TEST",
  STOP_COUGH_TEST: "STOP_COUGH_TEST",
  RUN_ANALYSIS: "RUN_ANALYSIS",
  GET_RESULT: "GET_RESULT",

  // Reports
  GENERATE_REPORT: "GENERATE_REPORT",
  GET_MY_REPORTS: "GET_MY_REPORTS",
  GET_PATIENT_REPORTS: "GET_PATIENT_REPORTS",
  OPEN_LATEST_REPORT: "OPEN_LATEST_REPORT",

  // Sharing
  SEND_REPORT_WHATSAPP: "SEND_REPORT_WHATSAPP",
  SEND_REPORT_EMAIL: "SEND_REPORT_EMAIL",
  COPY_REPORT_LINK: "COPY_REPORT_LINK",

  // Analytics
  GET_ANALYTICS_DASHBOARD: "GET_ANALYTICS_DASHBOARD",
  GET_HIGH_RISK_PATIENTS: "GET_HIGH_RISK_PATIENTS",
  GET_TODAY_STATS: "GET_TODAY_STATS",
  GET_MONTHLY_TRENDS: "GET_MONTHLY_TRENDS",
  EXPORT_ANALYTICS: "EXPORT_ANALYTICS",

  // Awareness
  WHAT_IS_ASTHMA: "WHAT_IS_ASTHMA",
  WHAT_IS_PNEUMONIA: "WHAT_IS_PNEUMONIA",
  ASTHMA_SYMPTOMS: "ASTHMA_SYMPTOMS",
  PREVENTION_TIPS: "PREVENTION_TIPS",
  WHEN_TO_SEE_DOCTOR: "WHEN_TO_SEE_DOCTOR"
} as const;
